name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0

    # * set release according to this page:
    # https://github.com/zmkfirmware/zmk/releases
